<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.4 setup script
 * Date: Sat, 13 Feb 2021 21:49:14 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: my_server [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'my_server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '/50Bq7Ke>bx9P\'<g_PPc~yZK#_U,BrbW';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
