#!/bin/bash

cd /var/www/html && tar -xvf wordpress_complete.tar.gz
unzip phpmyadmin.zip -d phpmyadmin

# Create socket directory (why postinstall php doesn't do that?!)
mkdir -p /run/php

# Add mysqli extenstion to php
sed -i 's/;extension=mysqli/extension=mysqli/g' "/etc/php/7.3/fpm/php.ini"

service nginx restart
service php7.3-fpm restart
service mysql restart
mysql -uroot -pSecretPassword123 --execute "`cat /var/www/html/wordpress.sql`"
mysql -u root -e "SET PASSWORD FOR root@'localhost' = PASSWORD('SecretPassword123');"
mv /var/www/html/config.inc.php /var/www/html/phpmyadmin
mv /var/www/html/phpmyadmin/phpMyAdmin-5.0.4-all-languages/* /var/www/html/phpmyadmin/
rm -rf /var/www/html/phpMyAdmin-5.0.4-all-languages

echo "service nginx start" >> /root/.zshrc
echo "service mysql start" >> /root/.zshrc
echo "service php7.3-fpm start" >> /root/.zshrc

echo "service nginx start" >> /root/.bashrc
echo "service mysql start" >> /root/.bashrc
echo "service php7.3-fpm start" >> /root/.bashrc

